version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"


python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: matplotlib==3.5.3
    - method: setuptools
      path: .
  system_packages: true

sphinx:
   configuration: doc/conf.py

formats:
   - pdf