language: python
dist: xenial
os:
  - linux
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.16.0 PANDAS_VERSION=0.16.2
  - NUMPY_VERSION=1.19.0 SCIPY_VERSION=1.5.2 PANDAS_VERSION=1.1.2

matrix:
  exclude:
  - python: "3.7"
    env: NUMPY_VERSION=1.9.2 SCIPY_VERSION=0.16.0 PANDAS_VERSION=0.16.2

addons:
  apt:
    packages:
      - g++
      - gfortran
      - cmake
      - libboost-all-dev
      - liblapack-dev
      - libopenblas-dev

# install dependencies
install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pathos
  - pip install numpy==$NUMPY_VERSION
  - pip install scipy==$SCIPY_VERSION
  - pip install pandas==$PANDAS_VERSION
  - pip install .
# run tests
script:
  - ./runtests.sh