name: Build wheels

on: workflow_dispatch

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Setup pip
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel

      - name: Build wheel
        run: python -m cibuildwheel --output-dir dist/
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-*

      - uses: actions/upload-artifact@v2
        with:
          path: ./dist/*.whl